name: Deploy GLPI

on:
  push:
    branches:
      - main  # Chạy tự động khi push vào nhánh main
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  pull-and-run:
    runs-on: ubuntu-latest  # Sử dụng môi trường runner của GitHub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Bước này chỉ cần nếu bạn muốn check mã nguồn từ repo

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Tên người dùng Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Mật khẩu hoặc token Docker Hub

      - name: SSH into server and Pull & Run Docker image
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: 192.168.89.11  # Địa chỉ IP của server
          username: ${{ secrets.SSH_USER }}  # Tên người dùng SSH trên server
          key: ${{ secrets.SSH_KEY }}  # SSH private key để kết nối với server
          script: |
            docker pull wannie419/glpi:latest  # Pull image từ Docker Hub
            docker run -d --name glpi -p 80:80 wannie419/glpi:latest  # Chạy container trên server
