name: Deploy GLPI

on:
  push:
    branches:
      - main  # Chạy tự động khi push vào main
  workflow_dispatch:
    inputs:
      environment:
        description: "Chọn môi trường để deploy"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # Sử dụng secret Docker username
          password: ${{ secrets.DOCKER_PASSWORD }}   # Sử dụng secret Docker password hoặc access token

      # Bước tiếp theo để build và push image
      - name: Set environment variables
        run: |
          if [ "${{ github.event.inputs.environment }}" == "production" ]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=staging" >> $GITHUB_ENV
          fi

      - name: Build GLPI Docker Image
        run: |
          docker build -t glpi:${{ env.TAG }} .
          docker tag glpi:${{ env.TAG }} ${{ secrets.DOCKER_USERNAME }}/glpi:${{ env.TAG }}

      - name: Push GLPI Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/glpi:${{ env.TAG }}
